service: re-view-app

useDotenv: true # 환경변수 자동 로드

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  deploymentBucket:
    name: ${env:AWS_BUCKET_NAME}
  cors:
  allowedOrigins:
    - "${env:FRONT_URL}"
  allowedHeaders:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
  allowedMethods:
    - OPTIONS
    - GET
    - POST
    - PUT
    - DELETE
  allowCredentials: true

  # 환경변수 설정
  environment:
    FRONT_URL: ${env:FRONT_URL}
    KAKAO_REST_API_KEY: ${env:KAKAO_REST_API_KEY}
    KAKAO_REDIRECT_URI: ${env:KAKAO_REDIRECT_URI}
    MONGO_URI: ${env:MONGO_URI}
    AWS_BUCKET_NAME: ${env:AWS_BUCKET_NAME}

  # IAM 역할 설정
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::${env:AWS_BUCKET_NAME}/*"

functions:
  app:
    handler: server.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: "*"
          cors:
            allowedOrigins:
              - "${env:FRONT_URL}"

plugins:
  - serverless-offline
