name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - "back/**"
      - ".github/workflows/backend-deploy.yml"
  pull_request:
    branches:
      - main
    paths:
      - "back/**"
      - ".github/workflows/backend-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install Serverless
        run: |
          npm install -g serverless

      - name: Install dependencies
        run: |
          cd back
          npm install

      - name: Deploy to Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          FRONT_URL: ${{ secrets.FRONT_URL }}
          TEST_FRONT_URL: ${{ secrets.TEST_FRONT_URL }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          NAVER_REDIRECT_URI: ${{ secrets.NAVER_REDIRECT_URI }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          IMG_SRC: ${{ secrets.IMG_SRC }}
          PUUUSH_WEB_HOOK_URL: ${{ secrets.PUUUSH_WEB_HOOK_URL }}
          DISCORD_FEEDBACK_WEB_HOOK_URL: ${{ secrets.DISCORD_FEEDBACK_WEB_HOOK_URL }}
          DISCORD_REPORT_WEB_HOOK_URL: ${{ secrets.DISCORD_REPORT_WEB_HOOK_URL }}
        run: |
          cd back
          npx serverless deploy
