name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install Dependencies
        run: |
          cd front
          pnpm install

      - name: Build Project
        run: |
          cd front
          pnpm build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_CLIENT_URL: ${{ secrets.VITE_CLIENT_URL }}
          VITE_KAKAO_REST_API_KEY: ${{ secrets.VITE_KAKAO_REST_API_KEY }}
          VITE_KAKAO_REDIRECT_URI: ${{ secrets.VITE_KAKAO_REDIRECT_URI }}
          VITE_KAKAO_LOGOUT_REDIRECT_URI: ${{ secrets.VITE_KAKAO_LOGOUT_REDIRECT_URI }}
          VITE_IMG_SRC: ${{ secrets.VITE_IMG_SRC }}

      - name: Deploy to Vercel
        run: |
          cd front
          vercel deploy --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }} --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
