name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - deploy
    paths:
      - "front/**"
      - ".github/workflows/frontend-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install Dependencies
        run: |
          cd front
          pnpm install

      - name: Build Project
        run: |
          cd front
          pnpm build

      - name: Add Vercel Environment Variables
        run: |
          vercel env add VITE_API_URL production --token=${{ secrets.API_URL }}
          vercel env add VITE_CLIENT_URL production --token=${{ secrets.FRONT_URL }}
          vercel env add VITE_KAKAO_REST_API_KEY production --token=${{ secrets.KAKAO_REST_API_KEY }}
          vercel env add VITE_KAKAO_REDIRECT_URI production --token=${{ secrets.KAKAO_REDIRECT_URI }}
          vercel env add VITE_KAKAO_LOGOUT_REDIRECT_URI production --token=${{ secrets.FRONT_URL }}
          vercel env add VITE_IMG_SRC production --token=${{ secrets.IMG_SRC }}

      - name: Deploy to Vercel
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }} --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
